### ISSUE TITLE
Questions about RB3 Deluxe

### ISSUE THREAD

**Issue by Milosz006** [hmxmilohax/rock-band-3-deluxe#239]
What's the default song list and how stable are they? I'll be playing on Wii. Also what instrument combinations are possible, I'll have 3 guitars, a drum kit and 1 microphone. Thank you for your time.

**Comment by shny-scott** [comment]
Deluxe does not add any songs, it has the exact same song count as vanilla Rock Band 3. Theoretically there should be no stability issues up to 1000 songs, as that's what Harmonix set the limit to (your mileage may vary beyond that). You will need to enable all instruments mode to play with 3 guitars (but do keep in mind you'll only be able to play songs that have keys, otherwise one player will be left doing nothing the whole song).
For future reference, this isn't what Github issues are for. Simple questions are better off answered in places like the Milohax Discord server, you likely would have had a response 8 hours ago.

**Comment by Milosz006** [comment]
> 

Thanks for the info! I searched for "help" and read the readme and saw nothing about a Discord, might be smart to add more information to your main page since Google doesn't find anything else.
