### ISSUE TITLE
Currentbeat sometimes reports wrong number, inconsistent countdowns

### ISSUE THREAD

**Issue by LinosM** [hmxmilohax/rock-band-3-deluxe#438]
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/15615513/f9d9ef22-197f-4b61-a932-b56dafbed17c)

**Comment by jnackmclain** [comment]
Fixed with [eaef71b](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/eaef71b8a531d9eeb0308ccab78546a7c20c544a)
I pieced it together that if the first note falls directly on beat 8, it fucks up with how the script works
so now i only track the first note if its above 10 which seems to fix the problem. Funny enough, you can also see this in the screenshot
One of my guesses is that that reported beat is left over from the last song/tracker
Regardless it's seemingly fixed
