### ISSUE TITLE
"The Future Soon" crashes the game when trying to play Harmonies

### ISSUE THREAD

**Issue by Bakartridge** [hmxmilohax/rock-band-3-deluxe#470]
Title kinda says it all, trying to play that song with harmonies (or view the harmonies chart with All-Instruments Mode) crashes the game, but standard vocals doesn't have it crash.

**Comment by r0bd0g** [comment]
~~The update folder for this song doesn't exist. Also means if there's a pro drums update, it's not working either.~~ Fixed
~~I noticed the same is true for "The Most Beautiful Girl in the Room". Try harmonies on that also if you want another crash. (I'll let you know if I find any other mistakes, but I'm not exactly looking for them.)~~ Fixed.

**Comment by r0bd0g** [comment]
~~The pro drums update is missing on "No One's Gonna Love You".~~ Fixed.

**Comment by r0bd0g** [comment]
~~ugc_5001428 "If Not Now, When?" doesn't include drum mix events in the pro drum update track. I don't know if that matters -- it probably does? It probably does have to be fixed. And I don't think it's the only song that's like this. I think saw another, but didn't note which song it was, though I expect to see it again eventually.~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5003105 (Tijuana Sweetheart - No Mercy) is missing its harmony update.~~ Fixed.

**Comment by r0bd0g** [comment]
~~UGC_5006348 (Rival Sons - Torture) is missing the harmonies update. (Is this an RBN2 song?)~~ Fixed.

**Comment by r0bd0g** [comment]
~~Something is weird with UGC_5005118 (The Material - Stay Here Forever), though idk if it's a problem.
RBHP provides a separate complete main midi file which does include the pro drums in it, but the original main midi may have included pro drums anyway?? And then it has the upgrade midi file with the three harmony tracks. Anyway, in the update file in this repo, it has the drums track and the harmony tracks, but somehow the tempo mapping is messed up??? I'm not sure what's going on with it.~~ Fixed

**Comment by r0bd0g** [comment]
The Future Soon should be fixed now, Bakartridge.
I'll mark off which of my reports are also fixed. I've gone through all songs that either came to Wii or had some non-pro drums update. So only like 1000 more RBN songs to look through.

**Comment by r0bd0g** [comment]
~~It's not a problem exactly?, but for whatever reason, UGC_5000895 (Scratching the Itch - Lemon Juice) includes the entire midi and not just the pro drums. As do UGC_5001375 (Scratching the Itch - You're My Everything), UGC_5001570 (James William Roy - Shiny Dark Bar), UGC_5002190 (Scratching the Itch - End of This), and UGC_5002309 (Your Horrible Smile - Shot at the Title).~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5001844 (Man Parts - Motorcide) is missing its pro drums update.
RBHP seems to have forgotten to actually supply the file, so... I guess somebody's going to actually have to create it, but it's straight-forward. I looked up the 2x bass pedal chart to see where the tom markers were supposed to go.~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5002660 (Clandestine - Disappear In You) is missing drum mix events and drum character animation events.
"If Not Now, When?" is also missing the animation events (or rather, event, singular), I just didn't notice it before. Somehow RBHP accidentally deleted all text events from these songs.~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5003300 (XTT - Fighting Back the Bullies)~~

~~RBHP mixed up midi file with Do You Want To Date My Avatar, which has a similar number, UGC_5003330. So the song will be completely broken if you try to play it right now. Additionally, there is no harmony upgrade, so the harmonies need to be removed from the dta.~~ Fixed.

~~I spoke with stackoverflow and he was able to find the original pro drums chart, which I guess I'll attach here so you don't have to go digging yourself.
[ugc_5003300_update.zip](https://github.com/hmxmilohax/rock-band-3-deluxe/files/13434590/ugc_5003300_update.zip)~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5003677 (Boney Mean - The Ending Is Death)
Is missing its pro drums upgrade. As far as I can tell, the file doesn't exist anywhere. And there doesn't seem to be any easy way to recreate it like there was with Motorcide. (I guess I'll let you know if I find a source for it.) If a source can't be found, or if the file isn't recreate, I guess this song should be removed from dta.~~ Fixed. But the drums update ought to be found if possible.

**Comment by r0bd0g** [comment]
~~UGC_5003723 (The Gracious Few - Honest Man)
The update midi has the wrong filename (it's like this on RBHP too), but it seems to be the correct file at least.~~ Fixed

**Comment by r0bd0g** [comment]
~~UGC_5003994 (GWAR - Let Us Slay)
is another one that seems to have been stripped of text events.~~ Fixed

**Comment by r0bd0g** [comment]
After merely opening every RBN upgrade and seeing what was inside, that's all of the issues that I was able to notice.

**Comment by r0bd0g** [comment]
Continuing now into official DLC, I guess? (There's probably a more appropriate place to post this kind of thing...)

~~thekill - The wrong drum mix events are used in the update file. The update uses drums0 where the stems show 5 tracks, meaning it should be drums2. This being incorrect will break the way the stems mute when playing on drums. (Expect missing to result in only the kick and left snare stems muting, leaving the cymbals/toms and right snare to continue to play -- very disorienting.)~~

~~(This song is fucky in vanilla, is what my investigation has revealed. They didn't put any drum mix events in the DLC on XBOX. On Wii it has drums1, which works fine on RB2 but, they didn't put any mix events in the RB3 update file, which makes is so that none of the drum tracks ever mute [which honestly is probably preferable to what usually happens on legacy songs]. I don't know if the vanilla RB3 update file on XBOX has the same issue or not, but my suspicion is that it does. I'm curious where you sourced this update file from, why it has the mix events as drums0.)~~ Fixed

beethovensc - This is the dumbest report you'll ever get. The first couple of beats on Medium I think might have the wrong drum mix? It's drums0 instead of drums1 like the rest of the difficulties. Seems to be a vanilla issue. I think the intention was likely drums1easynokick?

**Comment by exoticri** [comment]
can you please add any other dlc update issues to my pr #476 so that i can get a direct notification on what to fix?
