### ISSUE TITLE
Build keeps ignoring rank/origin updates on Xbox hardware for some songs

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#500]
Songs like El Scorcho keep reading as Rock Band 1/2 DLC when they should be reading as other sources (in this track's case it should be Track Pack: Volume 2). I see in the dtas that the lines are the same as the others in its said origin, but it chooses to ignore it for some reason. I've looked everywhere for the dta responsible for overriding this on Xbox hardware, but no luck. I don't have this issue on RPCS3.

**Comment by shny-scott** [comment]
Most track pack sources were removed some time ago as the general consensus was they were cluttering up the source menu (AC/DC Live was kept because its songs are not available for purchase as standard DLC). Sounds like you're just running an extremely old version of Deluxe in RPCS3, which you really should update.

**Comment by wintyre01** [comment]
Both versions are at the latest version. My thing is that the build allows the sources to pop up for songs like Afterlife, but not El Scorcho (or Buddy Holly for Volume 1 even)

**Comment by shny-scott** [comment]
Oh, are you specifically talking about the author finder additions to the MTV overlay? I assumed you meant in the song filtering menu, which is where they were removed from.

**Comment by wintyre01** [comment]
I am talking about the filtering menu. What I meant to say is for example, Afterlife has no issue showing up as Track Pack: Volume 2 (as well as every other track from that disc), while El Scorcho ignores it and just shows up as Rock Band 1/2 DLC. It’s more of a personal preference so I’m choosing to keep these filters in my build. It only affects a few tracks in my library, but it’s still puzzling why it does that when I’m certain all the changes that have been made by the team or my own personal additions are supposed to work. Like I said both RPCS3 and real Xbox are up to date, but real Xbox ignores some changes while RPCS3 does not

**Comment by shny-scott** [comment]
Well, if it's specifically an issue in your fork caused by changes you've made to that fork, I don't think a github issue on what is effectively an unrelated repo that doesn't even contain the bug is quite the right place to ask for help...
The issue is likely in changes you've made, or changes you've failed to make. We can't fix issues with code that did not come from this repo.

**Comment by wintyre01** [comment]
Found out what it was: I installed a DLC pack before my personal build and didn't clear the cache before doing so. Oops!
