### ISSUE TITLE
Crashing when trying to revert instrument spoofing to Vocals.

### ISSUE THREAD

**Issue by KingDamienHamster-kun** [hmxmilohax/rock-band-3-deluxe#567]
I usually use the Guitar slot when playing Rock Band 3 Deluxe, and I installed the latest nightly, then saw the controller remapping wasn't in my Deluxe Settings. Trying to reset the instrument type leads to a crash.

Nightly version: b932563
Controller: DualShock 3

**Comment by sourgummyes** [comment]
I can double confirm this issue is in the game. I have my arcade stick set to drums, and did the same exact thing, and the game freezes the console. 


Nightly version: d0aca0c (i think? thats what the title screen shows.)
Controller: Universal Arcade Stick F5000 V2 in PS3 mode.

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/26637455/e2708165-352d-403a-ad1f-3146eda35c0d

**Comment by jnackmclain** [comment]
fixed in latest dev, forgot to close
