### ISSUE TITLE
Outro Solos and End of Song Feedback

### ISSUE THREAD

**Issue by trishiskukky** [hmxmilohax/rock-band-3-deluxe#580]
I just feel like the end of song feedback should be delayed a bit when there's a solo that lasts until the end of the song/instrument's chart in order to show the player their solo "title" and the score they got. Thoughts?

**Comment by jnackmclain** [comment]
there are issues where the track can end too fast when the song ends, which is why we put it up as soon as the last note is hit.
which is an unfortunate issue with solos that end the song for sure, as we currently dont know how to check if we are in a solo, end feedback and even countdown overrides the solo box.

**Comment by trishiskukky** [comment]
I get what you're sayin'. No worries, dude.
