### ISSUE TITLE
Game erases all records of customs with each boot

### ISSUE THREAD

**Issue by ghost** [hmxmilohax/rock-band-3-deluxe#63]
#62 Think this has something to do with the previous custom issue. Whenever I successfully play a custom song and/or create a setlist with said song(s) in it, the game will ignore the fact that I ever had it loaded into the system to begin with by erasing my star records or reading the song as (Unknown Song) the next time I boot the game up, so it's almost as if I deleted the song when I closed the game, then reinstalled it under a new name somehow.
![Ass](https://user-images.githubusercontent.com/114825943/193881890-a74e4a8f-05db-4a34-9ad4-8c21b69bafd0.PNG)
![Ass2](https://user-images.githubusercontent.com/114825943/193881902-3d237cde-2bf7-4379-8253-86e42ee1b81c.PNG)

**Comment by jnackmclain** [comment]
I am fairly sure this is an issue with an invalid song ID for your customs. We have seen the behavior before with customs where scores were not saving, this was fixed with a properly formatted song_id within the songs.dta see this reference, but note it is song_id not songid 
![image](https://user-images.githubusercontent.com/55568980/193885049-7a257625-06cd-44ed-84ad-f10f66aea32a.jpeg)

**Comment by ghost** [comment]
Hmmm…what if the song ID is already a string (not in quotes though)? Example: (‘song_id’ ThisIsExileExplicit2) 🤔

In this case would I just have to change the file/con name altogether to just be a number and nothing else?

Sorry I’m being big dumb dumb lol

**Comment by jnackmclain** [comment]
Your song_id needs to be all numbers

**Comment by LocalH** [comment]
Filename of the CON/LIVE doesn't matter. It also has to be a number used by no other song, or it might conflict. The song_id is how the game tracks the song for save purposes. If you're converting the song via Onyx from another source, go into Preferences, 360 tab, and check "Use true number IDs instead of symbols on Xbox 360 RB files". Not sure if that does anything for straight conversion to PS3 (my primary platform is 360), but if not then a workaround would be to convert any songs from other formats to 360 CON first with the above option checked, then quick convert to PS3.

**Comment by ghost** [comment]
Fixed it. My records are now saving 😁
Unfortunately the issue with full band crashing the emulator in festivals with customs is still persisting (arenas seem to work now as long as I have a number in the song_id) 😞
