### ISSUE TITLE
[Feature Request] Allow RB3DX Wii to be loaded through Riivolution

### ISSUE THREAD

**Issue by zurgeg** [hmxmilohax/rock-band-3-deluxe#65]
Riivolution is used for [Custom Track Distributions](https://wiki.tockdom.com/wiki/Custom_Track_Distribution) for Mario Kart Wii, [NSMBW mods](https://horizon.miraheze.org/wiki/Mods) for New Super Mario Bros. Wii. A lot of people use Riivolution for mod loading. It patches data on the fly, instead of patching the files, making the build much smaller. I'd be glad to contribute to making this work.

**Comment by LlysiX** [comment]
gonna go ahead and add the resident rb wii modder @InvoxiPlayGames into this issue
I know nothing about wii modding, best I could personally do is rawfiles build actions for [RB3Enhanced](https://github.com/RBEnhanced/RB3Enhanced) players
if you can add in Riivolution support, send in a PR and I'll be glad to add it in

**Comment by InvoxiPlayGames** [comment]
Unlike NSMBW, Mario Kart Wii etc, Rock Band uses a huge archive file format rather than having all its files on the disc, and Riivolution only works for on-disc files - unless the ARK packing process can be made as solely a HDR edit + additional ARK, there's not much that adding Riivolution would do in terms of making the build much smaller (as of right now, you *can* make a very basic Riivolution XML for the rebuilt full set of ARKs so you don't have to rebuild the ISO)

**Comment by zurgeg** [comment]
> Unlike NSMBW, Mario Kart Wii etc, Rock Band uses a huge archive file format rather than having all its files on the disc, and Riivolution only works for on-disc files - unless the ARK packing process can be made as solely a HDR edit + additional ARK, there's not much that adding Riivolution would do in terms of making the build much smaller (as of right now, you _can_ make a very basic Riivolution XML for the rebuilt full set of ARKs so you don't have to rebuild the ISO)

IMO, it also would help with raw convenience. I'm pretty sure you can boot Riivolution via Letterbomb without HBC (don't quote me on that though), which would let people without cIOS/HBC to play this mod. I'd be glad to make a build script/GHAction for Riivolution though!

**Comment by zurgeg** [comment]
@InvoxiPlayGames So... where on disc do the files in `extracted_rb3/DATA/files/gen` go? Do they just go on the root of the disc? It's been awhile since I've used WIT so I have no clue.

**Comment by InvoxiPlayGames** [comment]
Files in the `gen` folder go in the `gen` folder on the disc.

> GHAction for Riivolution

A GitHub actions build would be a *bad idea* because building RB3DX for Wii right now requires a (legally obtained) dump of the base game. Including one in the repo would be a 1-way trip to the GitHub blackhole. (So would downloading it as part of the actions job - it's 4GB, they'll notice.)

**Comment by zurgeg** [comment]
I finished the Riivo patch, threw it into a random [repo](https://github.com/zurgeg/rb3dx-riivolution). I'll test in a minute.

**Comment by InvoxiPlayGames** [comment]
I'm not sure if the region name should be in the save file (the binary is 1:1 identical across regions, so the save file will be the same, unless someone out there bought *two discs* just for two different save files...). I'll get around to adding support for save redirection in RB3Enhanced using that path in case anyone moves over from Riivolution to RB3E.

I'd recommend putting the ARKs in `/rb3/gen/`, not in any subdirectories, as by default `/rb3/` is the folder rawfiles (including raw disc files like ARKs) get loaded from with RB3Enhanced.

Otherwise, that looks good.

**Comment by zurgeg** [comment]
> I'm not sure if the region name should be in the save file (the binary is 1:1 identical across regions, so the save file will be the same, unless someone out there bought _two discs_ just for two different save files...). I'll get around to adding support for save redirection in RB3Enhanced using that path in case anyone moves over from Riivolution to RB3E.
> 
> I'd recommend putting the ARKs in `/rb3/gen/`, not in any subdirectories, as by default `/rb3/` is the folder rawfiles (including raw disc files like ARKs) get loaded from with RB3Enhanced.
> 
> Otherwise, that looks good.

Just fixed all that up, once my disc finishes dumping I'll test it out on Dolphin.

**Comment by zurgeg** [comment]
Alright, I've got RB3DX loading with save redirection. I've almost finished making a easier CLI based build script for the Wii build.

**Comment by zurgeg** [comment]
Okay, CLI build wizard is done. Just need to add the part to execute `build.*` which requires some OS specific trickery, then it should be good to go.

**Comment by LlysiX** [comment]
it seems that your wizard pulls rb3dx before building, that isnt necessary as the build scripts already do that.

**Comment by zurgeg** [comment]
> it seems that your wizard pulls rb3dx before building, that isnt necessary as the build scripts already do that.

Good point.

**Comment by zurgeg** [comment]
Hey FYI, the build script on Windows fails due to `pause` at the end. Is there a way to bypass this?

**Comment by jnackmclain** [comment]
pause doesn’t fail a script, it only makes it so you can view the output

**Comment by zurgeg** [comment]
> pause doesn’t fail a script, it only makes it so you can view the output

It causes **my** script to fail. Sorry about the confusion 😅

**Comment by jnackmclain** [comment]
Remove the pause for the Wii build script then ezpz

**Comment by zurgeg** [comment]
> Remove the pause for the Wii build script then ezpz

From within my code? Or do you mean PR to remove [that part of the script](https://github.com/hmxmilohax/rock-band-3-deluxe/blob/wii/_build_wii.bat#L8)

**Comment by jnackmclain** [comment]
PR to remove it so it works for this feature.

**Comment by zurgeg** [comment]
> PR to remove it so it works for this feature.

Sweet. Let me just test the build script then I'll close this.

**Comment by LlysiX** [comment]
removing the pause is quite detrimental to the debugging process, if a dta file fails to be converted to dtb, it's a lot harder to know which file and where the error occurred without the pause since the CMD window will just disappear after its done without it.

**Comment by LocalH** [comment]
Just copy the existing bat file, add "nopause" to the filename, and then remove the pause in *that* copy of the bat file. best of both worlds

**Comment by zurgeg** [comment]
> Just copy the existing bat file, add "nopause" to the filename, and then remove the pause in _that_ copy of the bat file. best of both worlds

Will do, just give me a minute.
Edit: Done, #75

**Comment by zurgeg** [comment]
#75

**Comment by zurgeg** [comment]
Ugh, forgot to remove `pause` in the batch file. Is there a way to revise a PR so I don't fill the PR list with "pause", "unpause" etc.,?
