### ISSUE TITLE
A potential fix for songs with keys upgrades

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#663]
As you probably know, the songs that got keys upgrades had their venues flooded with camera spam at the end, strobe lights at certain points, the practice metronome removed (as mentioned in #467), and occasionally other issues too (Summer of '69 gets stuck on the drummer doing fancy stuff instead of playing). It was due to a bug in the MIDI Cleaner. I don't know if that was ever fixed but I think I have a solution for these songs.

For the camera and lights, try replacing the bugged [VENUE] track in the update .mid with the original. For the metronome, it's the same deal except with the [EVENTS] track.

**Comment by r0bd0g** [comment]
You can just delete the tracks from the update if you want to revert to the tracks from the vanilla midi (which should be done with the events track). The venue track needs to be updated though since old style venues won't work with keys.

When you say the camera got stuck on the drummer, was somebody playing on keys at the time? I think a lot of these updated venue tracks were never updated to include any camera cuts involving the keyboard player. So if normally the camera is trying to cut to the bassist or the guitarist but that character isn't present, the camera might get 'stuck' on the previous cut.

The strobe you're talking about might be cause by an RB3 bug with the [next] lighting event that causes all the nexts to build up and release all one after the other for some reason.

**Comment by SonicSBL** [comment]
The camera did get stuck when a keyboardist was playing. I also forgot to suggest adding keys camera cuts to the venue track.

I'm thinking about fixing these songs myself. How do I start?

**Comment by jnackmclain** [comment]
all of this should be fixed in latest nightly

**Comment by SonicSBL** [comment]
I just tested this out, and venues are now broken for these songs when playing any instrument. The camera just shows one continuous shot for the whole song.

**Comment by jnackmclain** [comment]
Okay we figured out that issue. fixed the missing venues in latest nightly

**Comment by SonicSBL** [comment]
The venues are still broken. Did you forget something?
