### ISSUE TITLE
Autoplay Modifier doesnt disconnect from rock central

### ISSUE THREAD

**Issue by gwarb** [hmxmilohax/rock-band-3-deluxe#74]
I autoplayed a song I mapped a venue track to (which currently has about a dozen other scores on it) and, even though saving was disabled, it still uploaded the bot's score to the leaderboards. The modifier should also disable connection to rock central servers alongside disabling saving and online play, if that's possible.

**Comment by jnackmclain** [comment]
theoretically it should now be impossible to play online if you have autoplay enabled
I was able to test leaderboard sending and having autoplay on will no longer submit leaderboards.
unknown if other backdoors exist (invites?)
fixed in [dd01fb3](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/dd01fb3dba6c05f56833e23402e3917aa6010d8e)
